project:
  type: website

website:
  title: "LoMo Case Challenge"
  navbar:
    left:
      - text: "Problem Statement"
        href: "problemstatement/problemstatement.html"
      - text: "Approach"
        href: "approach/approach.html"

format:
  html:
    theme: simple
    css: styles.css
    toc: true

editor: visual

